Parameters:
  pWLDestinationCidrBlock:
    Description: Please enter the workload VPC CIDR block
    Type: 10.192.0.0/16

  pSSDestinationCidrBlock:
    Description: Please enter the workload VPC CIDR block
    Type: 10.193.0.0/16

  pWLRouteTableId:
    Description: Please enter the route table ID created with the workload VPC deployment
    Type: rtb-12345

  pSSRouteTableId:
    Description: Please enter the route table ID created with the shared-services VPC deployment
    Type: rtb-12345

  pPeeringConnectionId:
    Description: Please enter the VPC peering connection id created with the VPC peering deployment
    Type: pcx-12345

Resources:
 myVPCPeeringRouteSS:
  Type: AWS::EC2::Route
  Properties:
    DestinationCidrBlock: Ref! pWLDestinationCidrBlock
    RouteTableId: Ref! pSSRouteTableId
    VpcPeeringConnectionId: Ref! pPeeringConnectionId

 myVPCPeeringRouteWL:
  Type: AWS::EC2::Route
  Properties:
    DestinationCidrBlock: Ref! pSSDestinationCidrBlock
    RouteTableId: Ref! pSSRouteTableId
    VpcPeeringConnectionId: Ref! pPeeringConnectionId
