Parameters:
  pWLDestinationCidrBlock:
    Description: Please enter the workload VPC CIDR block
    Type: String
    Default: 10.192.0.0/16

  pSSDestinationCidrBlock:
    Description: Please enter the workload VPC CIDR block
    Type: String
    Default: 10.193.0.0/16

  pWLRouteTableId:
    Description: Please enter the route table ID created with the workload VPC deployment
    Type: String
    Default: rtb-12345

  pSSRouteTableId:
    Description: Please enter the route table ID created with the shared-services VPC deployment
    Type: String
    Default: rtb-12345

  pPeeringConnectionId:
    Description: Please enter the VPC peering connection id created with the VPC peering deployment
    Type: String
    Default: pcx-12345

Resources:
 myVPCPeeringRouteSS:
  Type: AWS::EC2::Route
  Properties:
    RouteTableId: !Ref pSSRouteTableId
    VpcPeeringConnectionId: !Ref pPeeringConnectionId
    DestinationCidrBlock: !Ref pWLDestinationCidrBlock

 myVPCPeeringRouteWL:
  Type: AWS::EC2::Route
  Properties:
    RouteTableId: !Ref pWLRouteTableId
    DestinationCidrBlock: !Ref pSSDestinationCidrBlock
    VpcPeeringConnectionId: !Ref pPeeringConnectionId
